### ISSUE TITLE
First pre-train the emotion discriminator: where can find "val_hdf5_folder" filder?

### ISSUE THREAD

**Issue by hayk-manukyan-dev** [eeskimez/emotalkingface#19]
Hello, I already prepared the data. But I can't understand where is my "val_hdf5_folder" folder? After prepare data I have only one folder with hdf5 files. So, please let me know where can I find the hdf5 values folder or how can I create it (if I must to create it). Please help me to begin training process.

`python train.py -i /train_hdf5_folder/ -v /val_hdf5_folder/ -o ../models/mde/ --pre_train 1 --disc_emo 1 --lr_emo 1e-4`

After running the command I get this error
```
Traceback (most recent call last):
  File "emotalkingface/train.py", line 204, in <module>
    train()
  File "emotalkingface/train.py", line 126, in train
    dsetContainer = datagen.DatasetContainer(args)
  File "emotalkingface/datagen.py", line 45, in __init__
    emotion = emotion_dict[labels[2]]
IndexError: list index out of range
```

Thanks)))

**Comment by wangryhen** [comment]
Have you solved this problem? I met the same problem and need help.

**Comment by hayk-manukyan-dev** [comment]
> Have you solved this problem? I met the same problem and need help.

No, I haven’t any solution yet. I think there is no one to answer
