### ISSUE TITLE
Error when pre-train emoticon discriminator!

### ISSUE THREAD

**Issue by muxiddin19** [eeskimez/emotalkingface#6]
Traceback (most recent call last):
  File "train.py", line 204, in <module>
    train()
  File "train.py", line 130, in train
    train_loader = torch.utils.data.DataLoader(trainDset,
  File "C:\Users\INHA\anaconda3\envs\face\lib\site-packages\torch\utils\data\dataloader.py", line 268, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "C:\Users\INHA\anaconda3\envs\face\lib\site-packages\torch\utils\data\sampler.py", line 102, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by muxiddin19** [comment]
Can you please, give some solutions?

**Comment by eeskimez** [comment]
Hi, this looks like a missing data error. Have you prepared the training data and pointed the folder to the main script? 

Please check if the data preparation script works correctly and the output folder populates with samples.

I hope this helps!

Best,
Emre
